#pragma once

// temporary class just for testing porposes, probably going
// to replace with a model loader, preferebly the minecraft
// json format generated by blockbench, so i can load
// the minecraft models

class Cube : public Entity3D {
public:
    Vector3f position;
    Texture& texture;

    Cube(Vector3f thePosition, Texture& theTexture):
        position(thePosition),
        texture(theTexture)
    {}; // TODO: support multiple textures
    

    void draw(Camera& camera, FaceRenderer& fr) {
        Vector3f points[8] = {
            position + Vector3f(000,100,000),
            position + Vector3f(100,100,000),
            position + Vector3f(100,000,000),
            position + Vector3f(000,000,000),

            position + Vector3f(000,100,100),
            position + Vector3f(100,100,100),
            position + Vector3f(100,000,100),
            position + Vector3f(000,000,100),
        };

        int faces[][4] = {
            {4, 5, 1, 0},
            {3, 2, 6, 7},
            {4, 0, 3, 7},
            {5, 4, 7, 6},
            {1, 5, 6, 2},
            {0, 1, 2, 3},
        };
        
        for (auto& face : faces) {
            Vector3f fpoints[4] = {
                points[face[0]],
                points[face[1]],
                points[face[2]],
                points[face[3]],
            };
            fr.prepare(camera, fpoints, texture);
        }
    };
};
